server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-db
      jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: my-secret-key
  expiration: 3600000
